{{- $name := "analytics-service" }}
{{- $selector := "analytics" }}
kind: Service
apiVersion: v1
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: analytics
  selector:
    app.kubernetes.io/name: {{ $selector }}
    app.kubernetes.io/instance: trieve
