apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: trieve-clickhouse
  namespace: clickhouse
spec:
  configuration:
    users:
      default/password: {{ .Values.config.analytics.clickhousePassword }}
      # to allow access outside from kubernetes
      default/networks/ip:
        - 0.0.0.0/0
    clusters:
      - name: cluster1
        templates:
          podTemplate: clickhouse-pod-template
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    podTemplates:
      - name: clickhouse-pod-template
        spec:
          containers:
            - name: clickhouse
              image: trieve/clickhouse:latest
              digest: sha256:324f541975c43e96b5df6ede74632102d89172b703960bbf01f1842ccf48d240
              volumeMounts:
                - name: data-storage-vc
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc
                  mountPath: /var/log/clickhouse-server
              env:
                - name: EMBEDDING_SERVER_URL
                  value: {{ .Values.config.trieve.embeddingServerOriginBGEM3 }} # Cant use helm templating
                - name: CLICKHOUSE_ADMIN_PASSWORD
                  value: {{ .Values.config.analytics.clickhousePassword }}

    volumeClaimTemplates:
      - name: data-storage-vc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi
      - name: log-storage-vc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
