{{- range $index, $service := .Values.embeddings }}
{{- $port := (get $service "port") }}
{{- $name := (get $service "name") }}
{{- if ne $index 0 }}
---
{{- end }}
{{- $serviceName := (printf "embedding-%s" $name) }}
{{- $selector := (printf "embedding-%s" $name) }}
kind: Service
apiVersion: v1
metadata:
  name: {{ $serviceName }}
  labels:
    app.kubernetes.io/name: {{ $serviceName }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: svc
  selector:
    app.kubernetes.io/name: {{ $selector }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
