{{ $storage := (ternary "10Gi" "50Gi" (eq .Values.environment  "local")) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce  
{{- if ne .Values.environment "local" }}
  storageClassName: gp2
{{- else }}
  storageClassName: ""  
{{- end }}
  resources:
    requests:
      storage: {{ $storage }}
