{{- $selector := "tika" }}
kind: Service
apiVersion: v1
metadata:
  name: tika
  labels:
    app.kubernetes.io/name: tika
spec:
  type: ClusterIP
  ports:
    - port: 9998
      targetPort: 9998
      protocol: TCP
      name: tika
  selector:
    app.kubernetes.io/name: {{ $selector }}
    app.kubernetes.io/instance: trieve
