commonLabels:
  app.kubernetes.io/component: worker-queuebm25
nameSuffix: -bm25
resources:
  - ../base
images:
  - name: worker
    newName: trieve/queue-bm25-migration
patches:
  - target:
      kind: Deployment
      name: trieve-worker
    patch: |-
      - op: add
        path: /spec/replicas
        value: 0 # this deployment functions more like a "Job"
