apiVersion: batch/v1
kind: CronJob
metadata:
  name: collapsing-queries-cronjob
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: collapsing-queries
              image: trieve/clickhouse-collapse-query-script
              imagePullPolicy: IfNotPresent
              env:
                - name: CLICKHOUSE_DSN
                  valueFrom:
                    configMapKeyRef:
                      name: trieve-server-config
                      key: CLICKHOUSE_DSN
          restartPolicy: Never

