apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-queries-cronjob
spec:
  schedule: "1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cluster-queries
              image: trieve/clickhouse-clustering
              imagePullPolicy: IfNotPresent
              env:
                - name: ANTHROPIC_API_KEY
                  valueFrom:
                    configMapKeyRef:
                      name: trieve-server-config
                      key: ANTHROPIC_API_KEY
                - name: CLICKHOUSE_DSN
                  valueFrom:
                    configMapKeyRef:
                      name: trieve-server-config
                      key: CLICKHOUSE_DSN
          restartPolicy: Never
