apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgem3-embeddings-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgem3-embeddings-server
  template:
    metadata:
      labels:
        app: bgem3-embeddings-server
    spec:
      containers:
      - name: bgem3-embeddings-container
        image: ghcr.io/huggingface/text-embeddings-inference:86-1.1
        args: ["--model-id", "BAAI/bge-m3", "--revision", "main"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: shared-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: bgem3-server
spec:
  type: LoadBalancer
  ports:
    - port: 5556
      targetPort: 80
  selector:
    app: bgem3-embeddings-server
