apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jina-embeddings-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jina-embeddings-server
  template:
    metadata:
      labels:
        app: jina-embeddings-server
    spec:
      containers:
      - name: jina-embeddings-container
        image: ghcr.io/huggingface/text-embeddings-inference:86-1.1
        args: ["--model-id", "jinaai/jina-embeddings-v2-small-en", "--revision", "main"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: shared-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: jina-server
spec:
  type: LoadBalancer
  ports:
    - port: 9999
      targetPort: 80
  selector:
    app: jina-embeddings-server
