apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
spec:
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
      - name: tika
        image: apache/tika:2.9.1.0-full
        ports:
        - containerPort: 9998
        livenessProbe:
          httpGet:
            path: /version
            port: 9998
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /version
            port: 9998
          initialDelaySeconds: 5
          periodSeconds: 10


---

apiVersion: v1
kind: Service
metadata:
  name: tika
spec:
  ports:
  - port: 9998
    targetPort: 9998
  selector:
    app: tika
