name: rust test suite

on: 
  push:
    paths:
    - 'server/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'server/**'
    - '.github/workflows/**'
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: clechasseur/rs-clippy-check@v3
        with:
          args: --features runtime-env --manifest-path server/Cargo.toml
  redoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Vaccum
        run: npm install -g @quobix/vacuum
      - name: Generating OpenAPI spec
        run: cargo run --features runtime-env --manifest-path server/Cargo.toml --bin redoc_ci > openapi.json
      - name: Vaccum lint
        run: vacuum lint openapi.json

