name: search test suite

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "frontend/search/**"
      - "frontend/shared/**"
jobs:
  build-test:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: frontend
        run: yarn --frozen-lockfile
      - name: Running lint
        working-directory: frontend
        run: yarn build --filter search
  eslint:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: frontend
        run: yarn --frozen-lockfile
      - name: Running lint
        working-directory: frontend
        run: yarn lint:CI --filter search
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.0.4
        if: always()
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "./frontend/search/eslint_report.json"
