name: Typescript SDK test suite

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "clients/ts-sdk/**"

jobs:
  build-test:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Running tests
        run: yarn build --filter trieve-ts-sdk
  tests:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Running tests
        run: yarn vitest run
      # - name: Annotate Code Linting Results
      #   uses: ataylorme/eslint-annotate-action@1.0.4
      #   if: always()
      #   with:
      #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
      #     report-json: "./clients/ts-sdk/eslint_report.json"
